import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	plugins: [
		{
			name: 'copy-files',
			setup(build) {
				build.onEnd(() => {
					if (!fs.existsSync('dist')) {
						fs.mkdirSync('dist');
					}
					fs.copyFileSync('manifest.json', 'dist/manifest.json');
					if (fs.existsSync('styles.css')) {
						fs.copyFileSync('styles.css', 'dist/styles.css');
					}

					// Copy to vault if configured
					try {
						if (fs.existsSync('local-config.json')) {
							const config = JSON.parse(fs.readFileSync('local-config.json', 'utf8'));
							if (config.pluginPath && fs.existsSync(config.pluginPath)) {
								fs.copyFileSync('dist/main.js', path.join(config.pluginPath, 'main.js'));
								fs.copyFileSync('dist/manifest.json', path.join(config.pluginPath, 'manifest.json'));
								if (fs.existsSync('dist/styles.css')) {
									fs.copyFileSync('dist/styles.css', path.join(config.pluginPath, 'styles.css'));
								}
								console.log(`[Watch] Copied files to ${config.pluginPath}`);
							}
						}
					} catch (e) {
						console.error('[Watch] Failed to copy files to vault:', e);
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
